

#define FRONTPANEL_ANALOG_INPUT_LFO_FREQ        5
#define FRONTPANEL_ANALOG_INPUT_LFO_WAVEFORM    2
#define FRONTPANEL_ANALOG_INPUT_REPEAT_SPEED    7
#define FRONTPANEL_ANALOG_INPUT_VCO1_FINE_TUNE  3
#define FRONTPANEL_ANALOG_INPUT_VCO2_FINE_TUNE  4
#define FRONTPANEL_ANALOG_INPUT_VCO1_OCTAVE     0
#define FRONTPANEL_ANALOG_INPUT_VCO2_OCTAVE     1

#define FRONTPANEL_ANALOG_INPUT_LFO_SYNC_ON_OFF     6


#define FRONTPANEL_STATE_IDLE         0
#define FRONTPANEL_STATE_SET_VALUE    1
#define FRONTPANEL_STATE_UPDATE_GLISS 2

#define FRONTPANEL_BTN_STATE_IDLE   0
#define FRONTPANEL_BTN_WAIT_RELEASE 1
#define FRONTPANEL_BTN_END_RELEASE  2



void frontp_init(void);
void frontp_state_machine(void);


